---
title: "Understanding Statistical Inference"
author: "Gowtham Talluru"
date: "December 28, 2016"
output: word_document
---



# 1. Simulation Exercise
## 1.1: Overview: 
In this project distribution of sample statistics are compared with the theoretical
population statistics. As given in the question, mean and standard deviation of a 
random sample of exponential distribution (n=40, lambda=0.2) is compared to theoretical
mean and standard deviation

## 1.2: Simulation
1000 random exponential samples of lamda=0.2 are generated. Mean and Standard deviation
of these samples are calculated and tabulated in a data frame. The statistics of the mean 
and standard deviation are compared with the theoretical mean and standard deviation i.e 
1/lambda =1/0.2 = 5.
```{r, echo=TRUE}
results<-data.frame(id=numeric(),mean=numeric(),sd=numeric())

for(i in 1:1000){
x<-rexp(n=40, rate=0.2)
mean=mean(x)
sd=sd(x)
results[i,1]<-i
results[i,2]<-mean
results[i,3]<-sd
}
par(mfrow=c(1,2))
hist(results$mean, main = "Mean of n=40 random samples", col = "red")
abline(v=5, lwd=3, col="green")

hist(results$sd, main = "Sd of n=40 random samples", col="blue")
abline(v=5, lwd=3, col="green")

```

## 1.3: Explanation
It can be observed from the histograms that both the distributions are fairly 
normal. Both the distributions are centered at 5 which is the theoretical mean 
and standard deviation.


